spring.application.name=spring-enterprise-learning-lab
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.generate-unique-name=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.generate_statistics=true
feature.shipping-provider=fast
pagination.demo-records=10000
server.port=8080
