create table orders (
    id bigint generated by default as identity primary key,
    customer_name varchar(100) not null,
    status varchar(30) not null
);

create table pagination_records (
    id bigint generated by default as identity primary key,
    tenant_id varchar(50) not null,
    payload varchar(200) not null,
    created_at timestamp not null
);

create index idx_pagination_records_tenant_id_id
    on pagination_records(tenant_id, id);